### ISSUE TITLE
[REQUEST] SPADE-JSON format change

### ISSUE THREAD

**Issue by hassaanirshad** [CamFlow/libprovenance#33]
Hi,

Regarding ingestion of CamFlow output in SPADE-JSON format by SPADE can the format be updated as follows if possible:

1) No JSON array to contain all JSON objects (vertices, and edges).
2) One JSON object per line (i.e. no pretty printing). If the vertex or the edge JSON object contains any nested objects or arrays then that object or array would be in the same line as well.

Following is a sample file in the current format and the requested format:

**Current format sample:**
```
[{"type":"Entity","id":"<id>",
"annotations":{
"<key>":"<value>"}},
{
"type":"Activity","id":"<id>",
"annotations":{
"<key>":"<value>","<key>":"<value>"}
},
{
"type":"WasInformedBy","from":"<id>","to":"<id>",
"annotations":{
"id":"<id>"}
}]
```

**Same sample as above in requested format:**
```
{"type":"Entity","id":"<id>","annotations":{"<key>":"<value>"}}
{"type":"Activity","id":"<id>","annotations":{"<key>":"<value>","<key>":"<value>"}}
{"type":"WasInformedBy","from":"<id>","to":"<id>","annotations":{"id":"<id>"}}
```

Please let me know if there are any issues with the requested format.

Thank you.

**Comment by tfjmp** [comment]
Hi,

I made the changes, see the following commits:
https://github.com/CamFlow/libprovenance/commit/d9a2542bfd623e86bbcc3f59fa4f6e8bd0656871
https://github.com/CamFlow/libprovenance/commit/e5def574b89ecbeff0841b158e159d970ba0d886
https://github.com/CamFlow/camflowd/commit/70756ec08faddebad0052b871a11bb92bd35c229

Can you test the dev branch and let me know if it now works as you would expect?

```
git clone https://github.com/CamFlow/libprovenance
cd libprovenance
git checkout dev
make all && make install
```

```
https://github.com/CamFlow/camflowd
cd camflowd
git checkout dev
make all && make install
```

Don't forget to edit `/etc/camflowd.ini`

You may also need to install the dev branch of the kernel.

If it works as you would expect, we will roll out a release with those changes.

**Comment by hassaanirshad** [comment]
Hi,

Thank you for making the change, and laying out how to generate the updated format. It is fine overall but there is an empty line after about every 20 lines. The first empty line number is 2. Besides that it is fine. Please find attached the log file generated with the updated code. 
[audit.log.updated.gz](https://github.com/CamFlow/libprovenance/files/2497830/audit.log.updated.gz)

Thank you.

**Comment by tfjmp** [comment]
I think this should be fix with this latest commit:
https://github.com/CamFlow/camflowd/commit/09510a2960f82083a315c50ba3798a9c4002f87d

Let me know if there is any further issue.

**Comment by hassaanirshad** [comment]
There are no empty lines, and the format is as requested. Thank you for updating it.
