### ISSUE TITLE
Lexical error: invalid bytes in UTF8 string.

### ISSUE THREAD

**Issue by michael-hahn** [CamFlow/libprovenance#36]
CamFlow records may contain invalid UTF8 string when recording server address of a AF_INET6 packet. Example record below shows that the server address is invalid in UTF8:
```
"cf:AAACAAAAACBD9wAAAAAAAAEAAADE+3Y2AAAAAAAAAAA=": {
      "cf:id": "63299",
      "prov:type": "address",
      "cf:boot_id": 1,
      "cf:machine_id": "cf:913767364",
      "cf:version": 0,
      "cf:date": "2019:01:27T17:01:36",
      "cf:jiffies": "4294729314",
      "cf:epoch": 0,
      "cf:address": {
        "type": "AF_INET6",
        "host": "",
        "serv": "<98><9d>Z^ET^?"
      },
      "prov:label": "[address] IPV6 "
    }
```

**Comment by tfjmp** [comment]
I believe it is an address encoding issue occurring [here](https://github.com/CamFlow/libprovenance/blob/master/src/provenanceW3CJSON.c#L659) and [there](https://github.com/CamFlow/libprovenance/blob/master/src/provenanceW3CJSON.c#L662). 

Need to check what is the right combination of flags to pass to the `getnameinfo` function (see [here](http://man7.org/linux/man-pages/man3/getnameinfo.3.html) for details).

Also needs some reliable way to reproduce the issue to test if that indeed fix the problem.

**Comment by tfjmp** [comment]
Should have been fixed by: https://github.com/CamFlow/libprovenance/commit/b6906cea52e2faaa97000420bd7e0236c06b2b58

Further exploring issue relating to addresses.
